version: '3.8'

services:
  text-editor:
    build: .
    container_name: text-editor
    ports:
      - 8080:8080
    volumes:
      # Here link the folder you want to edit from this text editor
      - "./code:/root/code"
    environment:
      - PASSWORD=${PASSWORD}
      - PORT=8080

